#!/bin/bash
# If you're using my script, all you need to do is edit the following lines to work for you.
# Final zip will exist in "build" as "furnace-1.0.0-aosp_hammerhead.zip" for example
# If you are using a non-appended dt.image, you will need to add "--dt path/to/dt.img" and
# the appropriate lines for dtbTool to compile it, if not prebuilt.

# get OS (linux / Mac OS x)
IS_DARWIN=$(uname -a | grep Darwin)
if [ -n "$IS_DARWIN" ]; then
	CPUS=$(sysctl hw.ncpu | awk '{print $2}')
	DATE=gdate
else
	CPUS=$(grep "^processor" /proc/cpuinfo | wc -l)
	DATE=date
fi

build=/Volumes/kernel/android_kernel_htc_msm8974/ozip
export PATH=/Volumes/android/prebuilts/gcc/darwin-x86/arm/arm-eabi-4.7/bin:$PATH

kernel="Domination"
version="v1"
ramdisk=ramdisk
config="cm_m8_defconfig"
kerneltype="zImage"
jobcount=-j"`echo -e "$CPUS\t1.5" | awk '{print $1 * $2}'`"
ps=2048
base=0x00000000
kernel_offset=0x00008000
ramdisk_offset=0x02008000
tags_offset=0x01e00000
cmdline="console=ttyHSL0,115200,n8 androidboot.hardware=qcom user_debug=31 ehci-hcd.park=3 zcache eco_mode=0"

function cleanme {
	t1=$($DATE +%s)
	if [ -f arch/arm/boot/"$kerneltype" ]; then
		echo "  CLEAN   ozip"
	fi
	rm -rf ozip/boot.img
	rm -rf arch/arm/boot/"$kerneltype"
	mkdir -p ozip/system/lib/modules
	make clean "$jobcount" && make mrproper "$jobcount"
	echo "Working directory cleaned..."
	t2=$($DATE +%s)
	tmin=$(( (t2-t1)/60 ))
	tsec=$(( (t2-t1)%60 ))
	echo "Total time elapsed: $tmin minutes $tsec seconds"
}

rm -rf out
mkdir out
mkdir out/tmp
echo "Checking for build..."
if [ -f ozip/boot.img ]; then
	read -p "Previous build found, clean working directory..(y/n)? : " cchoice
	case "$cchoice" in
		y|Y )
			cleanme;;
		n|N )
			exit 0;;
		* )
			echo "Invalid...";;
	esac
	read -p "Begin build now..(y/n)? : " dchoice
	case "$dchoice" in
		y|Y)
			make "$config"
			make "$jobcount"
			exit 0;;
		n|N )
			exit 0;;
		* )
			echo "Invalid...";;
	esac
fi
echo "Extracting files..."
if [ -f arch/arm/boot/"$kerneltype" ]; then
	t1=$($DATE +%s)
	cp arch/arm/boot/"$kerneltype" out
	rm -rf ozip/system
	mkdir -p ozip/system/lib/modules
	find . -name "*.ko" -exec cp {} ozip/system/lib/modules \;
	if [ -f ozip/system/lib/modules/*.ko ]; then
		echo "Modules found."
	else
		echo "No modules"
		rm -rf ozip/system
	fi
else
	echo "Nothing has been made..."
	read -p "Clean working directory..(y/n)? : " achoice
	case "$achoice" in
		y|Y )
			cleanme;;
		n|N )
			echo "Whatever...";;
		* )
			echo "Invalid...";;
	esac
	read -p "Begin build now..(y/n)? : " bchoice
	case "$bchoice" in
		y|Y)
			t1=$($DATE +%s)
			make "$config"
			make "$jobcount"
			t2=$($DATE +%s)
			tmin=$(( (t2-t1)/60 ))
			tsec=$(( (t2-t1)%60 ))
			echo "Total time elapsed: $tmin minutes $tsec seconds"
			exit 0;;
		n|N )
			exit 0;;
		* )
			echo "Invalid...";;
	esac
fi

echo "Making dt.img..."
if [ -f arch/arm/boot/"$kerneltype" ]; then
	./dtbToolCM -o out/dt.img -s 2048 -d "htc,project-id = <" -p scripts/dtc/ arch/arm/boot/
	echo "dt.img created"
else
	echo "No build found..."
	exit 0;
fi


echo "Making ramdisk..."
if [ -d $ramdisk ]; then
	./mkbootfs $ramdisk | gzip > out/ramdisk.gz
else
	echo "No ramdisk found..."
	exit 0;
fi

echo "Making boot.img..."
if [ -f out/"$kerneltype" ]; then
	./mkbootimg --kernel out/"$kerneltype" --ramdisk out/ramdisk.gz --cmdline "$cmdline" --base $base --pagesize $ps --kernel_offset $kernel_offset --ramdisk_offset $ramdisk_offset --tags_offset $tags_offset --dt out/dt.img --output ozip/boot.img
else
	echo "No $kerneltype found..."
	exit 0;
fi

echo "Zipping..."
if [ -f arch/arm/boot/"$kerneltype" ]; then
	rm $build/$kernel-$version.zip
	cd ozip
	zip -r ../"$kernel"-$version.zip .
	mv ../"$kernel"-$version.zip $build
	cd ..
	rm -rf out ozip/system
	echo "Done..."
	echo "Output zip: $build/$kernel-$version.zip"
	t2=$($DATE +%s)
	tmin=$(( (t2-t1)/60 ))
	tsec=$(( (t2-t1)%60 ))
	echo "Total time elapsed: $tmin minutes $tsec seconds"
	exit 0;
else
	echo "No $kerneltype found..."
	exit 0;
fi
# Export script by Savoca
